import Foundation

/// # Shared domain vocabulary (cross-cutting value types)
///
/// These closed enums are the shared contract used across modules. They live in `Core`
/// — the foundational module every other module already imports — because both the
/// persistence layer (`Data`, which owns the SwiftData models that *store* these values)
/// and the feature layers (`Goals`, `Proposals`, which *drive* them) need them. Putting
/// them in `Core` avoids a dependency cycle: `Goals`/`Proposals` depend on `Data`, so
/// `Data` cannot depend back on them, yet `Data` must persist these values.
///
/// (Phase 0 seeded `TaskFlexibility`/`ConflictPolicy` in `Goals` and
/// `ProposalType`/`ProposalStatus` in `Proposals`. Phase 1 relocated them here — a move,
/// not a redefinition — so there remains exactly one definition of each.)

// MARK: - Goal task scheduling vocabulary (consumed by Phase 3A goals, Phase 4C conflicts)

/// How much latitude the scheduler has to move a goal task's block.
public enum TaskFlexibility: String, Equatable, Sendable, Codable, CaseIterable {
    case fixed, movable, optional
}

/// What conflict detection should do when a task's block overlaps another commitment.
public enum ConflictPolicy: String, Equatable, Sendable, Codable, CaseIterable {
    case block, warn, allow
}

// MARK: - Proposal vocabulary (consumed by Phase 4A proposals, Phase 5 tool registry)

/// The closed set of proposal action types. Adding a type is a deliberate change here:
/// Phase 4A's execution handlers, Phase 5's tool registry, and Phase 3A's schedule
/// previews all map to this same contract (AGENT_DESIGN §3).
public enum ProposalType: String, Equatable, Sendable, Codable, CaseIterable {
    case rememberFact = "remember_fact"
    case createAgentCalendarEvent = "create_agent_calendar_event"
    case updateAgentCalendarEvent = "update_agent_calendar_event"
    case modifyGoalPlan = "modify_goal_plan"
    case markGoalProgress = "mark_goal_progress"
    case snoozeOpenLoop = "snooze_open_loop"
    case dismissSignal = "dismiss_signal"
}

/// Proposal lifecycle states. Only `approved` ever triggers a handler; dismissed/snoozed/
/// expired never execute (the safety-critical negative cases tested in Phase 4A).
public enum ProposalStatus: String, Equatable, Sendable, Codable, CaseIterable {
    case pending
    case approved
    case dismissed
    case snoozed
    case expired
}

// MARK: - Memory provenance vocabulary (consumed by Phase 1 memory system)

/// Where a memory revision's value came from. Distinct from `DataSource` (which enumerates
/// external/on-device *integrations* the app degrades against): `MemorySource` also covers
/// first-party origins — direct user entry, agent inference, and system-generated facts —
/// so every memory revision can be honestly attributed.
public enum MemorySource: String, Equatable, Sendable, Codable, CaseIterable {
    /// Entered or confirmed directly by the user (highest trust).
    case user
    /// Derived from the user's real Google Calendar.
    case calendar
    /// Derived from Gmail content.
    case gmail
    /// Derived from HealthKit signals.
    case healthKit
    /// Ingested via the Shortcuts iMessage automation (untrusted external text).
    case iMessage
    /// Produced by the reasoning model.
    case reasoning
    /// Inferred by deterministic Swift logic (e.g., slip detection).
    case inference
    /// Generated by the system itself (e.g., a seeded default).
    case system
}
